# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Anime List"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run rspec tests
        run: bundle exec rspec
      - run: bundle exec oyencov translate_simplecov
      - run: bundle exec oyencov submit --git-commit-sha $GITHUB_SHA
        env: 
          OYENCOV_API_KEY: ${{ secrets.OYENCOV_API_KEY }}
